7.2.0+sp1.patch

diff --git a/.github/workflows/test-windows.yml b/.github/workflows/test-windows.yml
--- a/.github/workflows/test-windows.yml
+++ b/.github/workflows/test-windows.yml
@@ -8,7 +8,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.5", "3.6", "3.7", "3.8", "pypy3"]
+        python-version: ["3.5", "3.6", "3.7", "3.8", "pypy3.6"]
         architecture: ["x86", "x64"]
         include:
           - architecture: "x86"
@@ -19,11 +19,11 @@ jobs:
             platform-msbuild: "x64"
         exclude:
           # PyPy does not support 64-bit on Windows
-          - python-version: "pypy3"
+          - python-version: "pypy3.6"
             architecture: "x64"
     timeout-minutes: 30
 
-    name: Python ${{ matrix.python-version }} ${{ matrix.architecture }}
+    name: Python ${{ matrix.python-version }} ${{ matrix.architecture }} ${{ matrix.platform-vcvars }} ${{ matrix.platform-msbuild }}
 
     steps:
     - name: Checkout Pillow
@@ -34,6 +34,7 @@ jobs:
       with:
         repository: python-pillow/pillow-depends
         path: winbuild\depends
+        ref: 503ff2ff53e2f0446aa06a4a6c6cb17361b108e2
 
     - name: Cache pip
       uses: actions/cache@v1
@@ -47,12 +48,16 @@ jobs:
 
     # sets env: pythonLocation
     - name: Set up Python
-      uses: actions/setup-python@v1
+      uses: MatteoH2O1999/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
         architecture: ${{ matrix.architecture }}
+      env:
+        PIP_TRUSTED_HOST: pypi.python.org 
 
     - name: Set up TCL
+      env:
+        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       if: "contains(matrix.python-version, 'pypy')"
       run: Write-Host "::set-env name=TCL_LIBRARY::$env:pythonLocation\tcl\tcl8.5"
       shell: pwsh
@@ -60,10 +65,17 @@ jobs:
     - name: Print build system information
       run: python .github/workflows/system-info.py
 
-    - name: pip install wheel pytest pytest-cov
-      run: python -m pip install wheel pytest pytest-cov
+    - name: pip install 
+      env:
+        PIP_INDEX_URL: https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io
+      run: | 
+        python -m pip install setuptools<=47.3.2 # setuptools downgrade in case of python3.8 for windows build
+        python -m pip install wheel pytest>5 pytest-cov 
 
     - name: Prepare dependencies
+      env:
+        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
+        PIP_INDEX_URL: https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io
       run: |
         7z x winbuild\depends\nasm-2.14.02-win64.zip "-o$env:RUNNER_WORKSPACE\"
         Write-Host "::add-path::$env:RUNNER_WORKSPACE\nasm-2.14.02"
@@ -159,76 +171,78 @@ jobs:
       with:
         name: ${{ steps.wheel.outputs.dist }}
         path: dist\*.whl
+  # TODO: MINGW
+  # msys:
+  #   runs-on: windows-2019
 
-  msys:
-    runs-on: windows-2019
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       mingw: ["MINGW32", "MINGW64"]
+  #       include:
+  #         - mingw: "MINGW32"
+  #           package: "mingw-w64-i686"
+  #         - mingw: "MINGW64"
+  #           package: "mingw-w64-x86_64"
 
-    strategy:
-      fail-fast: false
-      matrix:
-        mingw: ["MINGW32", "MINGW64"]
-        include:
-          - mingw: "MINGW32"
-            package: "mingw-w64-i686"
-          - mingw: "MINGW64"
-            package: "mingw-w64-x86_64"
+  #   defaults:
+  #     run:
+  #       shell: bash.exe --login -eo pipefail "{0}"
+  #   env:
+  #     MSYSTEM: ${{ matrix.mingw }}
+  #     CHERE_INVOKING: 1
 
-    defaults:
-      run:
-        shell: bash.exe --login -eo pipefail "{0}"
-    env:
-      MSYSTEM: ${{ matrix.mingw }}
-      CHERE_INVOKING: 1
+  #   timeout-minutes: 30
+  #   name: MSYS2 ${{ matrix.mingw }}
 
-    timeout-minutes: 30
-    name: MSYS2 ${{ matrix.mingw }}
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-    steps:
-      - uses: actions/checkout@v2
+  #     - name: Set up shell
+  #       env:
+  #         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
+  #       run: echo ::add-path::C:\msys64\usr\bin\
+  #       shell: pwsh
 
-      - name: Set up shell
-        run: echo ::add-path::C:\msys64\usr\bin\
-        shell: pwsh
+  #     - name: Install Dependencies
+  #       run: |
+  #         pacman -S --noconfirm \
+  #             ${{ matrix.package }}-python3-pip \
+  #             ${{ matrix.package }}-python3-setuptools \
+  #             ${{ matrix.package }}-python3-pytest \
+  #             ${{ matrix.package }}-python3-pytest-cov \
+  #             ${{ matrix.package }}-python3-cffi \
+  #             ${{ matrix.package }}-python3-olefile \
+  #             ${{ matrix.package }}-python3-numpy \
+  #             ${{ matrix.package }}-python3-pyqt5 \
+  #             ${{ matrix.package }}-python3-numpy \
+  #             ${{ matrix.package }}-freetype \
+  #             ${{ matrix.package }}-lcms2 \
+  #             ${{ matrix.package }}-libwebp \
+  #             ${{ matrix.package }}-libjpeg-turbo \
+  #             ${{ matrix.package }}-openjpeg2 \
+  #             ${{ matrix.package }}-libimagequant \
+  #             ${{ matrix.package }}-libraqm \
+  #             ${{ matrix.package }}-ghostscript \
+  #             subversion
 
-      - name: Install Dependencies
-        run: |
-          pacman -S --noconfirm \
-              ${{ matrix.package }}-python3-pip \
-              ${{ matrix.package }}-python3-setuptools \
-              ${{ matrix.package }}-python3-pytest \
-              ${{ matrix.package }}-python3-pytest-cov \
-              ${{ matrix.package }}-python3-cffi \
-              ${{ matrix.package }}-python3-olefile \
-              ${{ matrix.package }}-python3-numpy \
-              ${{ matrix.package }}-python3-pyqt5 \
-              ${{ matrix.package }}-python3-numpy \
-              ${{ matrix.package }}-freetype \
-              ${{ matrix.package }}-lcms2 \
-              ${{ matrix.package }}-libwebp \
-              ${{ matrix.package }}-libjpeg-turbo \
-              ${{ matrix.package }}-openjpeg2 \
-              ${{ matrix.package }}-libimagequant \
-              ${{ matrix.package }}-libraqm \
-              ${{ matrix.package }}-ghostscript \
-              subversion
+  #         python3 -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' pyroma
 
-          python3 -m pip install pyroma
+  #         pushd depends && ./install_extra_test_images.sh && popd
 
-          pushd depends && ./install_extra_test_images.sh && popd
+  #     - name: Build Pillow
+  #       run: |
+  #         # libtiff is unable to open files
+  #         CFLAGS="-coverage" python3 setup.py build_ext --disable-tiff install
 
-      - name: Build Pillow
-        run: |
-          # libtiff is unable to open files
-          CFLAGS="-coverage" python3 setup.py build_ext --disable-tiff install
+  #     - name: Test Pillow
+  #       run: |
+  #         python3 selftest.py --installed
+  #         python3 -m pytest -vx --cov PIL --cov Tests --cov-report term --cov-report xml Tests
 
-      - name: Test Pillow
-        run: |
-          python3 selftest.py --installed
-          python3 -m pytest -vx --cov PIL --cov Tests --cov-report term --cov-report xml Tests
-
-      - name: Upload coverage
-        run: |
-          python3 -m pip install codecov
-          bash <(curl -s https://codecov.io/bash) -F GHA_Windows
-        env:
-          CODECOV_NAME: MSYS2 ${{ matrix.mingw }}
+  #     - name: Upload coverage
+  #       run: |
+  #         python3 -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' codecov
+  #         bash <(curl -s https://codecov.io/bash) -F GHA_Windows
+  #       env:
+  #         CODECOV_NAME: MSYS2 ${{ matrix.mingw }}
